name: Create Archive
on: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set Plugin Version
        uses: datamonsters/replace-action@master
        with:
          files: 'src/wp-vouched-verify.php'
          replacements: '[SEMVER]=${GITHUB_REF/refs\/tags\//}'
      - name: Zip Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r wp-vouched-verify.zip src
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: wp-vouched-verify.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
