name: Create Archive
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SetTag
        shell: bash
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set Plugin Version
        uses: datamonsters/replace-action@master
        with:
          files: 'src/wp-vouched-verify.php'
          replacements: "[SEMVER1]=${{ steps.get_version.outputs.VERSION }},[SEMVER2]=${{ steps.get_version.outputs.VERSION }}"
      - name: Zip Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r wp-vouched-verify.zip .
          working-directory: src
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: wp-vouched-verify.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
