name: Create Archive
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set Plugin Version
        uses: datamonsters/replace-action@master
        with:
          files: 'src/wp-vouched-verify.php'
          replacements: '[SEMVER]=${GITHUB_REF/refs\/tags\//}'
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'wp-vouched-verify.zip'
          path: 'src/'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wp-vouched-verify.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
