name: CI

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5 # or alternative dependency management
      - uses: php-actions/phpunit@v3
        env:
          TEST_NAME: dev
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
